WebApplication15/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication15.Data;

namespace WebApplication15.Pages
{
    public class CreateModel : PageModel
    {
        private readonly WebApplication15.Data.WebApplication15Context _context;

        public CreateModel(WebApplication15.Data.WebApplication15Context context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            if ((String)HttpContext.Session.GetString("username") != "admin")
                Response.Redirect("Request");
            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));
            return Page();
        }

        [BindProperty]
        public Request Request { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Request.Add(Request);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplication15/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication15.Data;

namespace WebApplication15.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplication15.Data.WebApplication15Context _context;

        public DeleteModel(WebApplication15.Data.WebApplication15Context context)
        {
            _context = context;
        }

        [BindProperty]
        public Request Request { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if ((String)HttpContext.Session.GetString("username") != "admin")
                Response.Redirect("Request");
            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));
            if (id == null)
            {
                return NotFound();
            }

            Request = await _context.Request.FirstOrDefaultAsync(m => m.username == id);

            if (Request == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Request = await _context.Request.FindAsync(id);

            if (Request != null)
            {
                _context.Request.Remove(Request);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplication15/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication15.Data;

namespace WebApplication15.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplication15.Data.WebApplication15Context _context;

        public DetailsModel(WebApplication15.Data.WebApplication15Context context)
        {
            _context = context;
        }

        public Request Request { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if ((String)HttpContext.Session.GetString("username") != "admin")
                Response.Redirect("Request");
            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));
            if (id == null)
            {
                return NotFound();
            }

            Request = await _context.Request.FirstOrDefaultAsync(m => m.username == id);

            if (Request == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApplication15/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication15.Data;

namespace WebApplication15.Pages
{
    public class EditModel : PageModel
    {
        private readonly WebApplication15.Data.WebApplication15Context _context;

        public EditModel(WebApplication15.Data.WebApplication15Context context)
        {
            _context = context;
        }

        [BindProperty]
        public Request Request { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if ((String)HttpContext.Session.GetString("username") != "admin")
                Response.Redirect("Request");
            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));
            if (id == null)
            {
                return NotFound();
            }

            Request = await _context.Request.FirstOrDefaultAsync(m => m.username == id);

            if (Request == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Request).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RequestExists(Request.username))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool RequestExists(string id)
        {
            return _context.Request.Any(e => e.username == id);

        }
    }
}

WebApplication15/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication15.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication15/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication15.Data;

namespace WebApplication15.Pages
{
    public class IndexModel : PageModel
    {
        private readonly WebApplication15.Data.WebApplication15Context _context;

        public IndexModel(WebApplication15.Data.WebApplication15Context context)
        {
            _context = context;
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.SetString("loggedin", "f");
            HttpContext.Session.SetString("username", "");
            return RedirectToPage("Login");
        }
        public IList<Request> Request { get;set; }

        public async Task OnGetAsync()
        {
            Request = await _context.Request.ToListAsync();
            if ((String)HttpContext.Session.GetString("username") != "admin")
                Response.Redirect("Request");

            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));
        }

        public IActionResult OnPostUpdate()
        {
                return RedirectToPage("Update");
        }
    }
}

WebApplication15/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication15.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication15/Pages/Request.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace WebApplication15.Pages
{
    //comment
    public class RequestModel : PageModel
    {
        public void OnGet()
        {
            if (((String)HttpContext.Session.GetString("loggedin") != "t"))
                Response.Redirect("login");
            if ((String)HttpContext.Session.GetString("username") == "admin")
                Response.Redirect("Index");


            HttpContext.Session.SetString("loggedin", "t");
            HttpContext.Session.SetString("username", (String)HttpContext.Session.GetString("username"));

        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.SetString("loggedin", "f");
            HttpContext.Session.SetString("username", "");
            return RedirectToPage("Login");
        }
        public IActionResult OnPostUpdate()
        {

            return RedirectToPage("Update");
        }
        public IActionResult OnPostRequest()
        {
            String query = "INSERT INTO dbo.request (username,status) VALUES (@username, @status)";
            String connectionString = "Data Source=192.168.0.212;Initial Catalog=testDB;User ID=sa;Password=7v!SkU{r";
            using (SqlConnection connection2 = new SqlConnection(
                connectionString))
            {
                SqlCommand command = new SqlCommand(
                    query, connection2);
                command.Parameters.AddWithValue("@username", (String)HttpContext.Session.GetString("username"));
                command.Parameters.AddWithValue("@Status", 0);
                connection2.Open();
                try
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Console.WriteLine(String.Format("{0}, {1}",
                                reader[0], reader[1]));
                        }
                    }
                    //lb_error.Visible = false;
                }
                catch (Microsoft.Data.SqlClient.SqlException) //request is pending
                {

                }
            }
            return RedirectToPage("Request");
        }

        public IActionResult OnPostSwitch()
        {
            String query = "INSERT INTO dbo.request (username,status) VALUES (@username, @status)";
            String connectionString = "Data Source=192.168.0.212;Initial Catalog=testDB;User ID=sa;Password=7v!SkU{r";
            using (SqlConnection connection2 = new SqlConnection(
                connectionString))
            {
                SqlCommand command = new SqlCommand(
                    query, connection2);
                command.Parameters.AddWithValue("@username", (String)HttpContext.Session.GetString("username"));
                command.Parameters.AddWithValue("@Status", 0);
                connection2.Open();
                try
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Console.WriteLine(String.Format("{0}, {1}",
                                reader[0], reader[1]));
                        }
                    }
                    //lb_error.Visible = false;
                }
                catch (System.Data.SqlClient.SqlException) //request is pending
                {

                }
            }
            return RedirectToPage("Request");
        }
    }
}

WebApplication15/Pages/login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace WebApplication15.Pages
{
    public class loginModel : PageModel
    {
        public string Message { get; set; }

        public string User => (string)TempData[nameof(User)];

        public string Pass => (string)TempData[nameof(Pass)];



        public void OnGet()
        {

        }

        public IActionResult OnPostLogin([FromForm] string user, [FromForm] string pass)
        {

            if ((user != null) && (pass != null))
            {
                //TempData["loggedIn"] = "t";
                //TempData["username"] = user;
                HttpContext.Session.SetString("loggedin", "t");
                HttpContext.Session.SetString("username", user);
                String query = "SELECT username, password FROM dbo.users WHERE username = @username AND password = @password;";
                String connectionString = "Data Source=192.168.0.212;Initial Catalog=testDB;User ID=sa;Password=7v!SkU{r";
                using (SqlConnection connection = new SqlConnection(
                    connectionString))
                {
                    SqlCommand command = new SqlCommand(
                        query, connection);
                    command.Parameters.AddWithValue("@username", user);
                    command.Parameters.AddWithValue("@password", encrypt.Encrypt(pass));
                    connection.Open();
                    try
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            /* while (reader.Read())
                             {
                                 Console.WriteLine(String.Format("{0}, {1}",
                                     reader[0], reader[1]));
                                 string test = reader.GetString(0);
                                 string test2 = reader.GetString(1);

                             }*/
                            if (reader.Read())
                            {
                                if (reader.GetString(0) == "admin")
                                {
                                    connection.Close();
                                    return RedirectToPage("Index");
                                }
                                else
                                {
                                    connection.Close();
                                    return RedirectToPage("Request");
                                }
                            }
                            //test
                            else //incorrect login information
                            {
                                connection.Close();
                                return RedirectToPage("login");
                            }

                        }



                    }
                    catch (System.Data.SqlClient.SqlException)
                    {
                        //incorrect login information
                        connection.Close();
                        return RedirectToPage("login");
                    }
                }






            }
            else
                return RedirectToPage("login");

        }

        public IActionResult OnPostCreate()
        {
            return RedirectToPage("NewAccount");
        }



    }
}

WebApplication15/Pages/Create.cshtml
@page
@model WebApplication15.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Request.username" class="control-label"></label>
                <input asp-for="Request.username" class="form-control" />
                <span asp-validation-for="Request.username" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Request.status" /> @Html.DisplayNameFor(model => model.Request.status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication15/Pages/Delete.cshtml
@page
@model WebApplication15.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Request.status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Request.status)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Request.username" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

WebApplication15/Pages/Details.cshtml
@page
@model WebApplication15.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Request.status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Request.status)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Request.username">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

WebApplication15/Pages/Edit.cshtml
@page
@model WebApplication15.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Request.username" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Request.status" /> @Html.DisplayNameFor(model => model.Request.status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication15/Pages/Index.cshtml
@page
@model WebApplication15.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<div>
    <h1 class="display-4">Welcome user to the CDA Training Web App</h1>

    <p class="text-center">
        <img alt="" src="https://d1hbpr09pwz0sk.cloudfront.net/logo_url/critical-design-associates-inc-ab9cc379" class="center"/>
    </p>

    
   



    <form method="post" asp-page="Login">
        <div class="form-group">

         
            <p><button id="btn1" type="submit" class="btn btn-primary" asp-page-handler="Logout">Logout</button></p>
            
            <p><button type="submit" class="btn btn-primary" asp-page-handler="Update">Update Password</button></p>
        </div>


    </form>




</div>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Request[0].username)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Request) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.status)
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.username">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.username">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.username">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication15/Pages/NewAccount.cshtml
@page
@model WebApplication15.Pages.NewAccountModel
@{
}

<div class="text-left">
    

    <form method="post" asp-page="NewAccount">
        <div class="form-group">
            <p>Username</p>
            <p><input asp-for="User" id="Text1" type="text" /></p>  
            <p>Password</p>
            <p><input asp-for="Pass1" id="Text2" type="password" /></p>
            <p>Re-enter Password</p>
            <p><input asp-for="Pass2" id="Text3" type="password" /></p>
         </div>
            <p><button type="submit" class="btn btn-primary">Create Account</button></p>
    </form>

</div>

WebApplication15/Pages/Request.cshtml
@page
@model WebApplication15.Pages.RequestModel
@{
}

<div>
    <h1 class="display-4">Welcome user to the CDA Training Web App</h1>

    <p class="text-center">
        <img alt="" src="https://d1hbpr09pwz0sk.cloudfront.net/logo_url/critical-design-associates-inc-ab9cc379" class="center"/>
    </p>

    <p class="text-center">
        
    
    <form method="post" asp-page="Request">
        <div class="form-group">
        
 
        <p><button type="submit" class="btn btn-primary" asp-page-handler="Request">Request Network Account</button></p>
        
        <p><button type="submit" class="btn btn-primary" asp-page-handler="Update">Update Password</button></p>
        
        <p><button type="submit" class="btn btn-primary" asp-page-handler="Logout">Logout</button></p> 

             </div>
            
        </form>
    </p>



</div>

WebApplication15/Pages/Update.cshtml
@page
@model WebApplication15.Pages.UpdateModel
@{
}


<div class="text-left">
    <h1 class="display-4">CDA Training Web App!</h1>


    <form method="post" asp-page="Update">
        <div class="form-group">
            <p>Current Password</p>
            <p><input asp-for="Pass" id="Text1" type="password" asp-page-handler="Update"/></p>  
            <p>New Password</p>
            <p><input asp-for="newPass1" id="Text1" type="password" asp-page-handler="Update"/></p>
            <p>Confirm New Password</p>
            <p><input asp-for="newPass2" id="Text1" type="password" asp-page-handler="Update"/></p>
         </div>
            <p><button id="btn1" type="submit" class="btn btn-primary" asp-page-handler="Update">Update</button></p>

    </form>


</div>

WebApplication15/Pages/login.cshtml
@page
@model WebApplication15.Pages.loginModel
@{
}

<div class="text-left">
    <h1 class="display-4">CDA Training Web App Login!</h1>


    <form method="post" asp-page="Login">
        <div class="form-group">
            <p>Username</p>
            <p><input asp-for="User" id="Text1" type="text" asp-page-handler="Login"/></p>  
            <p>Password</p>
            <p><input asp-for="Pass" id="Text1" type="password" asp-page-handler="Login"/></p>
         </div>
            <p><button id="btn1" type="submit" class="btn btn-primary" asp-page-handler="Login">Login</button></p>


         <p><button type="submit" class="btn btn-primary" asp-page-handler="Create">Create Account</button></p>

    </form>


</div>